# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Create symlinks
# ln -s ~/.config/zsh/zshrc ~/.zshrc && ln -s ~/.config/zsh/zshenv ~/.zshenv
# ln -s ~/.config/zsh/p10k.zsh ~/.p10k.zsh
# Install base packages if needed
# sudo apt install curl wget git
# Install autojump
# sudo apt install autojump
# Install atuin 
# bash <(curl https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh) && atuin import auto
# Install Antigen 
# mkdir -p ~/.config/zsh && curl -L git.io/antigen > ~/.config/zsh/antigen.zsh
# Install zsh
# sudo apt install zsh
# Set zsh to default shell
# chsh -s $(which zsh)
# Create zshenv 
# ls ~/.config/zsh/zshenv || (touch ~/.config/zsh/zshenv)
# Install Zellij 
# mkdir -p ~/.local/bin && cd ~/.local/bin && wget https://github.com/zellij-org/zellij/releases/download/v0.39.2/zellij-x86_64-unknown-linux-musl.tar.gz && tar -xvf zellij-x86_64-unknown-linux-musl.tar.gz && chmod +x zellij && rm -rf zellij-x86_64-unknown-linux-musl.tar.gz && cd -
# install lsd (ls replacement)
# sudo apt install lsd

source ~/.config/zsh/antigen.zsh

source ~/.config/zsh/aws.zsh

source ~/.config/zsh/aliases.zsh


# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle aws
antigen bundle docker
antigen bundle docker-compose
# antigen bundle fzf # CTRL+R, replaced by Atuin
antigen bundle autojump # J
antigen bundle marlonrichert/zsh-autocomplete@main # Context based suggestions (on bottom of screen) navigate with TAB
antigen bundle zsh-users/zsh-autosuggestions # History based suggestions (fills current command with suggestion) validate with Left Arrow
antigen bundle pip
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(atuin init zsh)"
